openapi: 3.1.1
info:
  title: Data Models
  version: 1.0.0
components:
  schemas:
    User:
      required:
        - id
        - email
        - passwordHash
        - username
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        username:
          type: string
        passwordHash:
          type: string
          format: password
        refreshTokens:
          type: array
          items:
            $ref: "#/components/schemas/RefreshToken"

    Page:
      type: object
      required:
        - id
        - content
        - userId
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        userId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    RefreshToken:
      type: object
      required:
        - token
        - userId
        - expires
      properties:
        token:
          type: string
        userId:
          type: integer
        expires:
          type: string
          format: date-time

    TokenPayload:
      type: object
      required:
        - sub
        - username
        - email
      properties:
        sub:
          type: string
        username:
          type: string
        email:
          type: string
    AuthProfile:
      type: object
      required:
        - username
        - email
        - id
      properties:
        username:
          type: string
        email:
          type: string
        id:
          type: string
