/*
 * Data Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenPayload {
    #[serde(rename = "sub")]
    pub sub: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl TokenPayload {
    pub fn new(sub: String, username: String, email: String) -> TokenPayload {
        TokenPayload {
            sub,
            username,
            email,
        }
    }
}
