// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswjhGeyBUEhQGpbRSfd4b6nWjjpGgtz4',
    appId: '1:853613213908:web:36f550ce8664877d94e341',
    messagingSenderId: '853613213908',
    projectId: 'taskjournal-e3f94',
    authDomain: 'taskjournal-e3f94.firebaseapp.com',
    storageBucket: 'taskjournal-e3f94.appspot.com',
    measurementId: 'G-5FF1LPJNNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMoM2vdE_W2lcQHG8h0Cv8ZoRBoADtyc',
    appId: '1:853613213908:android:d1819c2266a03b3794e341',
    messagingSenderId: '853613213908',
    projectId: 'taskjournal-e3f94',
    storageBucket: 'taskjournal-e3f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxAMjPAJcz_3rZlQkxS7L4ZsW2A2juw8',
    appId: '1:853613213908:ios:5328a6fdf313d70294e341',
    messagingSenderId: '853613213908',
    projectId: 'taskjournal-e3f94',
    storageBucket: 'taskjournal-e3f94.appspot.com',
    iosClientId: '853613213908-6pd2agfmdruk0gd068ako5gd8fel13lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskjournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxAMjPAJcz_3rZlQkxS7L4ZsW2A2juw8',
    appId: '1:853613213908:ios:fbe2e0eef4ada13194e341',
    messagingSenderId: '853613213908',
    projectId: 'taskjournal-e3f94',
    storageBucket: 'taskjournal-e3f94.appspot.com',
    iosClientId: '853613213908-2j9v5n00pgud60jencojeh99ta2h25dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskjournal.RunnerTests',
  );
}
